services:
  api:
    container_name: todo-api
    hostname: todo-api
    depends_on:
      - db
    build: .
    networks:
      - default

  db:
    container_name: db
    hostname: db
    image: mysql:latest
    networks:
      - default

networks:
  default:
    name: todolist
    driver: bridge
