services:
  api:
    container_name: todo-api
    hostname: todo-api
    depends_on:
      - db
    build: .
    env_file:
      - api/.env
  db:
    container_name: db
    hostname: db
    image: mysql:latest
    env_file:
      - db/.env
