version: '3.7'

services:
  web:
    container_name: todo-api
    hostname: todo-api
    build: .
    env_file:
      - src/.env
    ports:
      - "5000:5000"
    volumes:
      - ./src/test.db:/app/test.db
